### ISSUE TITLE
Necromancer - Level 2 Spell

### ISSUE THREAD

**Issue by MedianAura** [subtledoctor/Scales_of_Balance#2]
Upon sleeping with a Necromancer and level 2 spell memorized will crash the game to desktop.

I made a clean install of the game and just installed the master version of Scale of Balance and only loaded the module that change Wyzard for a test and as soon as you try to sleep with any level 2 spell memorized the game crash to desktop.

I can include the crash dump file if it's any useful.

**Comment by subtledoctor** [comment]
So weird! I just tested and confirmed that sleeping with a Necromancer causes crashes - on BGT only, not in the EE engine. Thank you for narrowing it down to 2nd-level spells... but I have no idea what could cause that. Possibly an EE-only opcode crept into a kit ability, and it causes a crash when the rest script runs (I've had something similar with my Bladesinger kit and players who use the "heal when resting" gameplay option.)

I'll take a look.

**Comment by MedianAura** [comment]
I haven't tried with BGT but the crash happen on my hand on BG2EE ...My last attempt I deleted my entire Override folder made Steam repair the game files and then just install the Wyzards component and got into the game with a necromancer and as soon as I could learned a single level 2 spell sleep and crash again.
